### ISSUE TITLE
Sign error of dihedral coeffs of EMIM?

### ISSUE THREAD

**Issue by gullbrekken** [orlandoacevedo/IL#5]
In the EMIM_scale0.8.itp file the CW-NA-CA-HA dihedral has coefficients V1 to V4: -2.7     5.65   0.355    0. See line 140 in the file. However, in the original paper "Development of OPLS-AA Force Field Parameters for 68 Unique Ionic Liquids" and in the SI of "Revisiting OPLS Force Field Parameters for Ionic Liquid Simulations", the coefficients for this dihedral are: -2.700 -5.650 0.355. So the second coefficient is negative, while it is positive in the ITP file.
I want to simulate a system containing EMIM, so my question is, which value is correct?

**Comment by gullbrekken** [comment]
I could add that the relevant coefficient is also positive (5.65) in the EMIM.itp file.

**Comment by orlandoacevedo** [comment]
Thank you for catching this typo. The value should be negative as reported in the papers (and as listed for BMIM and OMIM). I have updated both EMIM files.

**Comment by gullbrekken** [comment]
Thank you!
